Sign in(FORM)
Code-the-Dream-School/gg-pac-team3-monorepo pull request #13
Opened 2024-08-17 01:12 UTC by canilo1

Hey everyone, I thought it was good practice to create a separate PR for any new features. Technically, the sign-in form is a new feature, even though it's very similar to the sign-up form, so I made a new PR. I hope that doesn't bother anyone.

2024-08-17 01:13 UTC, canilo1 commented
![image_2024-08-16_181125272](https://github.com/user-attachments/assets/e0187154-e49c-4e4e-9f30-8f7fa6afdc56)

2024-08-17 20:20 UTC, ElijahMSmith commented
I'm going to ignore the first three commits for the signup form since they are addressed in the other PR. For something like this that depends on other code that is under review, I would either just stick them together or wait for that to get merged before opening another PR so that those commits don't appear in this PR too. That said, the way you've approached this is fine and it's just a limitation of GitHub so don't worry about it here.

2024-08-17 20:24 UTC, ElijahMSmith requested changes
Let's hold off on this MR until the SignUp form is finished and merged.

2024-08-17 20:24 UTC, ElijahMSmith commented on frontend/src/pages/frontPage/Panel.jsx
> +      {/* <SignUp isLoggedIn={isLoggedIn} /> */}
Let's not keep any dead code we aren't using.

2024-08-17 20:24 UTC, ElijahMSmith commented on frontend/src/pages/frontPage/Panel.jsx
> -      <SignUp isLoggedIn={isLoggedIn} />
The other PR I made a request to only show the popup when I click "register", which we should also do here when I click "login". Let's fix it in that branch, merge those changes, then rebase this branch and do the same thing.

2024-08-17 20:24 UTC, ElijahMSmith commented on frontend/src/components/layout/signIn.jsx
This should be `SignIn.jsx` for consistency.

2024-08-17 20:24 UTC, ElijahMSmith commented on frontend/src/components/layout/SignIn.module.css
> +.container {
Let's also be consistent here in class names and make them all camelCase.

2024-08-23 01:29 UTC, canilo1 commented
The Sign-Up page has everything that the Sign-In format has, so I'm going to close this branch since it's no longer needed. It's merged, by the way.

2024-08-23 01:29 UTC, closed without merging